// ─── INITIAL MOCK DATA ────────────────────────────────────────────────────────

export const INITIAL_JOBS = [
  {
    id: 'job-001',
    title: 'Senior Frontend Engineer',
    department: 'Engineering',
    location: 'Remote / Hyderabad',
    type: 'Full-time',
    experience: '3–5 years',
    salary: '₹18L – ₹28L',
    status: 'Active',
    description: 'We are looking for an experienced Frontend Engineer to lead our UI development using React, TypeScript, and modern tooling. You will collaborate with design and backend teams to ship high-quality features.',
    requiredSkills: ['React', 'TypeScript', 'Tailwind CSS', 'REST APIs', 'Git'],
    niceToHave: ['Next.js', 'GraphQL', 'Figma', 'Testing (Jest)'],
    postedDate: '2025-05-10',
    applicantCount: 34,
    deadline: '2025-06-15',
  },
  {
    id: 'job-002',
    title: 'Machine Learning Engineer',
    department: 'AI & Data',
    location: 'Bangalore',
    type: 'Full-time',
    experience: '2–4 years',
    salary: '₹20L – ₹35L',
    status: 'Active',
    description: 'Join our AI team to build and deploy ML models that power our recommendation and ranking systems.',
    requiredSkills: ['Python', 'TensorFlow', 'PyTorch', 'Scikit-learn', 'SQL'],
    niceToHave: ['MLflow', 'Kubernetes', 'AWS SageMaker'],
    postedDate: '2025-05-12',
    applicantCount: 21,
    deadline: '2025-06-20',
  },
  {
    id: 'job-003',
    title: 'Product Designer (UI/UX)',
    department: 'Design',
    location: 'Remote',
    type: 'Full-time',
    experience: '2–5 years',
    salary: '₹14L – ₹22L',
    status: 'Active',
    description: 'Design intuitive user experiences across our product suite. Partner closely with product and engineering to define and ship design systems, wireframes, and prototypes.',
    requiredSkills: ['Figma', 'User Research', 'Prototyping', 'Design Systems', 'Usability Testing'],
    niceToHave: ['Motion Design', 'Framer', 'Accessibility'],
    postedDate: '2025-05-08',
    applicantCount: 18,
    deadline: '2025-06-10',
  },
  {
    id: 'job-004',
    title: 'Backend Engineer (Node.js)',
    department: 'Engineering',
    location: 'Hyderabad',
    type: 'Full-time',
    experience: '2–4 years',
    salary: '₹16L – ₹26L',
    status: 'Paused',
    description: 'Build scalable APIs and microservices for our platform. You will own critical backend systems, integrate third-party services, and ensure high availability.',
    requiredSkills: ['Node.js', 'Express', 'PostgreSQL', 'REST APIs', 'Docker'],
    niceToHave: ['Redis', 'AWS', 'Kafka', 'TypeScript'],
    postedDate: '2025-04-28',
    applicantCount: 27,
    deadline: '2025-06-01',
  },
];

export const INITIAL_CANDIDATES = [
  {
    id: 'cand-001',
    name: 'Arjun Sharma',
    email: 'arjun.sharma@email.com',
    phone: '+91 98765 43210',
    location: 'Hyderabad, TS',
    jobId: 'job-001',
    jobTitle: 'Senior Frontend Engineer',
    status: 'Applied',
    aiScore: 92,
    experience: '4 years',
    currentRole: 'Frontend Developer at Infosys',
    education: 'B.Tech CSE – JNTU Hyderabad',
    appliedDate: '2025-05-14',
    resumeUrl: '#',
    matchedSkills: ['React', 'TypeScript', 'Tailwind CSS', 'REST APIs', 'Git'],
    missingSkills: [],
    aiReasoning: 'Candidate has 4 years of hands-on React experience with TypeScript in production environments. Strong portfolio showcasing component-based architecture and state management. All required skills are present with excellent depth. Minor gap in Next.js which is a nice-to-have.',
    interviewDate: null,
    notes: 'Strong profile – fast-track to technical round.',
    linkedIn: 'linkedin.com/in/arjunsharma',
    avatar: null,
  },
  {
    id: 'cand-002',
    name: 'Priya Menon',
    email: 'priya.menon@email.com',
    phone: '+91 87654 32109',
    location: 'Bangalore, KA',
    jobId: 'job-001',
    jobTitle: 'Senior Frontend Engineer',
    status: 'Hold',
    aiScore: 74,
    experience: '3 years',
    currentRole: 'UI Developer at Wipro',
    education: 'M.Sc CS – Manipal University',
    appliedDate: '2025-05-15',
    resumeUrl: '#',
    matchedSkills: ['React', 'REST APIs', 'Git'],
    missingSkills: ['TypeScript', 'Tailwind CSS'],
    aiReasoning: 'Candidate demonstrates solid React fundamentals and 3 years of relevant experience. However, TypeScript proficiency is limited to basic types, and Tailwind CSS experience is absent. CSS-in-JS alternative skills suggest adaptability. Recommend a brief skills check before advancing.',
    interviewDate: null,
    notes: 'Good communication in initial screening call.',
    linkedIn: 'linkedin.com/in/priyamenon',
    avatar: null,
  },
  {
    id: 'cand-003',
    name: 'Karthik Reddy',
    email: 'karthik.r@email.com',
    phone: '+91 76543 21098',
    location: 'Chennai, TN',
    jobId: 'job-001',
    jobTitle: 'Senior Frontend Engineer',
    status: 'Selected',
    aiScore: 96,
    experience: '5 years',
    currentRole: 'Senior Engineer at Zoho',
    education: 'B.E. IT – Anna University',
    appliedDate: '2025-05-13',
    resumeUrl: '#',
    matchedSkills: ['React', 'TypeScript', 'Tailwind CSS', 'REST APIs', 'Git', 'Next.js', 'GraphQL'],
    missingSkills: [],
    aiReasoning: 'Exceptional candidate with 5 years of production React/TypeScript experience. Open-source contributions demonstrate advanced skills. All required AND nice-to-have skills present. Next.js & GraphQL expertise is a strong bonus for our roadmap. Highly recommend expedited offer.',
    interviewDate: '2025-05-22',
    notes: 'Interviewed well. Offer letter being prepared.',
    linkedIn: 'linkedin.com/in/karthikreddydev',
    avatar: null,
  },
  {
    id: 'cand-004',
    name: 'Sneha Agarwal',
    email: 'sneha.agarwal@email.com',
    phone: '+91 65432 10987',
    location: 'Pune, MH',
    jobId: 'job-001',
    jobTitle: 'Senior Frontend Engineer',
    status: 'Rejected',
    aiScore: 41,
    experience: '1 year',
    currentRole: 'Junior Developer at Accenture',
    education: 'BCA – Symbiosis',
    appliedDate: '2025-05-16',
    resumeUrl: '#',
    matchedSkills: ['React', 'Git'],
    missingSkills: ['TypeScript', 'Tailwind CSS', 'REST APIs'],
    aiReasoning: 'Candidate has foundational React knowledge but lacks the 3+ years of experience required for a senior role. TypeScript and REST API integration skills are undeveloped. Portfolio projects are academic rather than production-grade. Not a fit for this senior position at this time.',
    interviewDate: null,
    notes: 'Consider for junior/intern openings in future.',
    linkedIn: '',
    avatar: null,
  },
  {
    id: 'cand-005',
    name: 'Rahul Nair',
    email: 'rahul.nair@email.com',
    phone: '+91 54321 09876',
    location: 'Kochi, KL',
    jobId: 'job-002',
    jobTitle: 'Machine Learning Engineer',
    status: 'Applied',
    aiScore: 88,
    experience: '3 years',
    currentRole: 'Data Scientist at TCS',
    education: 'M.Tech AI – IIT Madras',
    appliedDate: '2025-05-17',
    resumeUrl: '#',
    matchedSkills: ['Python', 'TensorFlow', 'Scikit-learn', 'SQL'],
    missingSkills: ['PyTorch'],
    aiReasoning: 'Strong ML background from IIT Madras. Production experience with TensorFlow models in NLP and computer vision. SQL and data engineering skills are well-developed. PyTorch familiarity is limited but the candidate expressed interest in transitioning. Recommend advancing.',
    interviewDate: null,
    notes: '',
    linkedIn: 'linkedin.com/in/rahulnair-ml',
    avatar: null,
  },
  {
    id: 'cand-006',
    name: 'Divya Krishnan',
    email: 'divya.k@email.com',
    phone: '+91 43210 98765',
    location: 'Mumbai, MH',
    jobId: 'job-003',
    jobTitle: 'Product Designer (UI/UX)',
    status: 'Selected',
    aiScore: 91,
    experience: '4 years',
    currentRole: 'UX Designer at PhonePe',
    education: 'B.Des – NID Ahmedabad',
    appliedDate: '2025-05-11',
    resumeUrl: '#',
    matchedSkills: ['Figma', 'User Research', 'Prototyping', 'Design Systems', 'Usability Testing'],
    missingSkills: [],
    aiReasoning: 'Outstanding designer with NID pedigree and 4 years in a fintech product environment. Deep expertise in design systems and component libraries. Portfolio demonstrates exceptional product thinking and attention to accessibility. All required skills met with strong depth.',
    interviewDate: '2025-05-20',
    notes: 'Second round scheduled with VP Design.',
    linkedIn: 'linkedin.com/in/divyakrishnan',
    avatar: null,
  },
  {
    id: 'cand-007',
    name: 'Vikram Patel',
    email: 'vikram.patel@email.com',
    phone: '+91 32109 87654',
    location: 'Ahmedabad, GJ',
    jobId: 'job-004',
    jobTitle: 'Backend Engineer (Node.js)',
    status: 'Applied',
    aiScore: 79,
    experience: '3 years',
    currentRole: 'Node.js Developer at Zerodha',
    education: 'B.Tech IT – GTU',
    appliedDate: '2025-05-18',
    resumeUrl: '#',
    matchedSkills: ['Node.js', 'Express', 'PostgreSQL', 'Docker'],
    missingSkills: ['REST APIs'],
    aiReasoning: 'Solid backend experience with Node.js and microservices at Zerodha, a high-scale fintech platform. Docker deployment skills are strong. REST API design is likely present but not explicitly listed; recommend clarifying during interview. Good candidate overall.',
    interviewDate: null,
    notes: '',
    linkedIn: '',
    avatar: null,
  },
];

export const INITIAL_INTERVIEWS = [
  {
    id: 'int-001',
    candidateId: 'cand-003',
    candidateName: 'Karthik Reddy',
    jobTitle: 'Senior Frontend Engineer',
    round: 'Technical Round 2',
    date: '2025-05-22',
    time: '10:00 AM',
    duration: 60,
    mode: 'Video Call',
    interviewers: ['Rohit Verma (Eng Lead)', 'Meena Rao (CTO)'],
    status: 'Scheduled',
    meetingLink: 'https://meet.google.com/abc-defg-hij',
    notes: 'Focus on system design and React performance optimization.',
  },
  {
    id: 'int-002',
    candidateId: 'cand-006',
    candidateName: 'Divya Krishnan',
    jobTitle: 'Product Designer (UI/UX)',
    round: 'Portfolio Review',
    date: '2025-05-20',
    time: '2:30 PM',
    duration: 45,
    mode: 'Video Call',
    interviewers: ['Anjali Desai (VP Design)'],
    status: 'Completed',
    meetingLink: 'https://meet.google.com/xyz-1234-uvw',
    notes: 'Candidate presented 3 case studies. Excellent.',
  },
  {
    id: 'int-003',
    candidateId: 'cand-005',
    candidateName: 'Rahul Nair',
    jobTitle: 'Machine Learning Engineer',
    round: 'Screening Call',
    date: '2025-05-25',
    time: '11:00 AM',
    duration: 30,
    mode: 'Phone',
    interviewers: ['Suresh Kumar (AI Team)'],
    status: 'Scheduled',
    meetingLink: '',
    notes: 'Verify PyTorch transition timeline.',
  },
];

export const DEPARTMENTS = [
  'Engineering', 'AI & Data', 'Design', 'Product', 'Marketing',
  'Operations', 'HR', 'Finance', 'Sales', 'Legal',
];

export const JOB_TYPES = ['Full-time', 'Part-time', 'Contract', 'Internship', 'Freelance'];

export const EXPERIENCE_LEVELS = [
  '0–1 years (Fresher)', '1–2 years', '2–4 years', '3–5 years',
  '4–6 years', '5–8 years', '8+ years (Senior/Lead)',
];

export const SKILLS_POOL = [
  'React', 'Vue', 'Angular', 'Next.js', 'TypeScript', 'JavaScript',
  'Python', 'Node.js', 'Express', 'Django', 'FastAPI', 'Java', 'Spring Boot',
  'Tailwind CSS', 'CSS', 'SCSS', 'HTML', 'Figma', 'Sketch',
  'PostgreSQL', 'MySQL', 'MongoDB', 'Redis', 'Elasticsearch',
  'AWS', 'GCP', 'Azure', 'Docker', 'Kubernetes', 'Terraform', 'CI/CD',
  'TensorFlow', 'PyTorch', 'Scikit-learn', 'SQL', 'Pandas', 'NumPy',
  'REST APIs', 'GraphQL', 'gRPC', 'Microservices', 'Kafka',
  'Git', 'Jira', 'Agile', 'Scrum', 'Product Management', 'User Research',
  'Design Systems', 'Prototyping', 'Usability Testing', 'SEO', 'Analytics',
];


// Extra candidates to populate Pipeline view (matching screenshot)
INITIAL_CANDIDATES.push(
  {
    id: 'cand-007', name: 'Ramoju Naresh', email: 'ramoju.naresh@email.com',
    phone: '+91 97000 11111', location: 'Hyderabad, TS',
    jobId: 'job-001', jobTitle: 'Senior Frontend Engineer',
    status: 'Applied', aiScore: 55, experience: '1 year',
    currentRole: 'Junior Developer', education: 'B.Tech IT, JNTU',
    matchedSkills: ['React', 'JavaScript'],
    missingSkills: ['TypeScript', 'REST APIs', 'Git'],
    aiReasoning: 'Basic React knowledge but lacks TypeScript and production-level experience for a senior role.',
    appliedDate: '2025-05-20', notes: '',
  },
  {
    id: 'cand-008', name: 'Anumulla Manoj Reddy', email: 'manoj.reddy@email.com',
    phone: '+91 98000 22222', location: 'Bangalore, KA',
    jobId: 'job-002', jobTitle: 'Machine Learning Engineer',
    status: 'Applied', aiScore: 61, experience: '2 years',
    currentRole: 'Data Analyst at Deloitte', education: 'M.Sc. Data Science, BITS Pilani',
    matchedSkills: ['Python', 'Scikit-learn', 'SQL'],
    missingSkills: ['TensorFlow', 'PyTorch'],
    aiReasoning: 'Good Python/statistics background but missing deep learning frameworks critical for the ML Engineer role.',
    appliedDate: '2025-05-21', notes: '',
  }
)
